packages:
  - scripts/*
  - packages/internal/*
  - packages/internal/lint-configs/*
  - packages/vben/*
  - packages/vben/@core/base/*
  - packages/vben/@core/ui-kit/*
  - packages/vben/@core/forward/*
  - packages/vben/@core/*
  - packages/vben/effects/*
  - packages/vben/business/*
  - packages/marketing/fingerprint/*
  - packages/marketing/*
  - apps/*

catalog:
  "@ant-design/icons-vue": ^7.0.1
  "@ast-grep/napi": ^0.31.1
  "@changesets/changelog-github": ^0.5.0
  "@changesets/cli": ^2.27.12
  "@changesets/git": ^3.0.2
  "@clack/prompts": ^0.8.2
  "@commitlint/cli": ^19.7.1
  "@commitlint/config-conventional": ^19.7.1
  "@ctrl/tinycolor": ^4.1.0
  "@eslint/js": ^9.20.0
  "@faker-js/faker": ^9.4.0
  "@iconify/json": ^2.2.305
  "@iconify/tailwind": ^1.2.0
  "@iconify/vue": ^4.3.0
  "@intlify/core-base": ^10.0.5
  "@intlify/unplugin-vue-i18n": ^6.0.3
  "@jspm/generator": ^2.5.0
  "@manypkg/get-packages": ^2.2.2
  "@nestjs/cli": ^10.4.9
  "@nestjs/common": ^10.4.15
  "@nestjs/config": ^3.3.0
  "@nestjs/core": ^10.4.15
  "@nestjs/jwt": ^10.2.0
  "@nestjs/mapped-types": "*"
  "@nestjs/passport": ^10.0.3
  "@nestjs/platform-fastify": ^10.4.15
  "@nestjs/schematics": ^10.2.3
  "@nestjs/sequelize": ^10.0.1
  "@nestjs/testing": ^10.4.15
  "@nolebase/vitepress-plugin-git-changelog": ^2.13.2
  "@playwright/test": ^1.50.1
  "@pnpm/workspace.read-manifest": ^1000.0.2
  "@stylistic/stylelint-plugin": ^3.1.1
  "@tailwindcss/nesting": 0.0.0-insiders.565cd3e
  "@tailwindcss/typography": ^0.5.16
  "@tanstack/vue-query": ^5.66.0
  "@tanstack/vue-store": ^0.6.0
  "@types/archiver": ^6.0.3
  "@types/eslint": ^9.6.1
  "@types/html-minifier-terser": ^7.0.2
  "@types/jest": ^29.5.14
  "@types/jsonwebtoken": ^9.0.8
  "@types/lodash-es": ^4.17.12
  "@types/lodash.clonedeep": ^4.5.9
  "@types/lodash.get": ^4.4.9
  "@types/lodash.isequal": ^4.5.8
  "@types/md5": ^2.3.5
  "@types/node": ^20.17.17
  "@types/nprogress": ^0.2.3
  "@types/passport-jwt": ^4.0.1
  "@types/platform": ^1.3.6
  "@types/postcss-import": ^14.0.3
  "@types/qrcode": ^1.5.5
  "@types/sortablejs": ^1.15.8
  "@types/supertest": ^6.0.2
  "@types/user-agents": ^1.0.4
  "@typescript-eslint/eslint-plugin": ^7.18.0
  "@typescript-eslint/parser": ^7.18.0
  "@vee-validate/zod": ^4.15.0
  "@vite-pwa/vitepress": ^0.5.3
  "@vitejs/plugin-vue": ^5.2.1
  "@vitejs/plugin-vue-jsx": ^4.1.1
  "@vue/reactivity": ^3.5.13
  "@vue/shared": ^3.5.13
  "@vue/test-utils": ^2.4.6
  "@vueuse/core": ^12.5.0
  "@vueuse/integrations": ^12.5.0
  '@vueuse/motion': ^2.2.6
  ant-design-vue: ^4.2.6
  archiver: ^7.0.1
  argon2: ^0.41.1
  autoprefixer: ^10.4.20
  axios: ^1.7.9
  axios-mock-adapter: ^2.1.0
  cac: ^6.7.14
  chalk: ^5.4.1
  cheerio: 1.0.0
  circular-dependency-scanner: ^2.3.0
  class-transformer: ^0.5.1
  class-validator: ^0.14.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.0.1
  consola: ^3.4.0
  cross-env: ^7.0.3
  cspell: ^8.17.3
  cssnano: ^7.0.6
  custom-electron-titlebar: ^4.2.8
  cz-git: ^1.11.0
  czg: ^1.11.0
  dayjs: ^1.11.13
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^10.0.0
  echarts: ^5.6.0
  electron: ^34.5.4
  electron-builder: ^25.1.8
  element-plus: ^2.9.4
  eslint: ^8.57.1
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.4.0
  eslint-plugin-command: ^0.2.7
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-jsdoc: ^50.6.3
  eslint-plugin-jsonc: ^2.19.1
  eslint-plugin-n: ^17.15.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^3.9.1
  eslint-plugin-prettier: ^5.2.3
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^9.32.0
  execa: ^9.5.2
  fastify: ^4.29.0
  find-up: ^7.0.0
  fs-extra: ^11.3.0
  get-port: ^7.1.0
  globals: ^15.14.0
  h3: ^1.15.0
  happy-dom: ^15.11.7
  html-minifier-terser: ^7.2.0
  husky: ^9.1.7
  is-ci: ^3.0.1
  is-what: ^5.2.0
  jest: ^29.7.0
  jsonc-eslint-parser: ^2.4.0
  jsonwebtoken: ^9.0.2
  lint-staged: ^15.4.3
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  lodash.clonedeep: ^4.5.0
  lodash.get: ^4.4.2
  lodash.isequal: ^4.5.0
  lucide-vue-next: ^0.465.0
  md5: ^2.3.0
  medium-zoom: ^1.1.0
  naive-ui: ^2.41.0
  nitropack: ^2.10.4
  node-scp: ^0.0.23
  nprogress: ^0.2.0
  ora: ^8.2.0
  p-queue: ^8.1.0
  passport-jwt: ^4.0.1
  pinia: 2.2.2
  pinia-plugin-persistedstate: ^4.2.0
  pkg-types: ^1.3.1
  platform: ^1.3.6
  playwright: ^1.50.1
  postcss: ^8.5.1
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.8.0
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.3
  postcss-scss: ^4.0.9
  prettier: ^3.5.0
  prettier-plugin-tailwindcss: ^0.6.11
  publint: ^0.2.12
  qrcode: ^1.5.4
  radix-vue: ^1.9.13
  readline: ^1.3.0
  reflect-metadata: ^0.2.2
  resolve.exports: ^2.0.3
  rimraf: ^6.0.1
  rollup: ^4.34.6
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-visualizer: ^5.14.0
  rxjs: ^7.8.1
  sass: 1.80.6
  sequelize: ^6.37.5
  sequelize-typescript: ^2.1.6
  shelljs: ^0.8.5
  sortablejs: ^1.15.6
  source-map-support: ^0.5.21
  sqlite3: ^5.1.7
  stylelint: ^16.14.1
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.6.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.11.0
  supertest: ^7.0.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  theme-colors: ^0.1.0
  ts-jest: ^29.2.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsx: ^4.19.2
  turbo: ^2.4.0
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unplugin-element-plus: ^0.8.0
  user-agents: ^1.1.448
  uuid: ^11.0.5
  vee-validate: ^4.15.0
  vite: ^6.1.0
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: 4.2.1
  vite-plugin-electron: ^0.29.0
  vite-plugin-electron-renderer: ^0.14.6
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^0.21.1
  vite-plugin-vue-devtools: ^7.7.1
  vitepress: ^1.6.3
  vitepress-plugin-group-icons: ^1.3.5
  vitest: 3.0.5
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
  vue-i18n: ^10.0.5
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  vxe-pc-ui: ^4.4.8
  vxe-table: ^4.10.0
  watermark-js-plus: ^1.5.7
  zod: ^3.24.1
  zod-defaults: ^0.1.3
  tippy.js: ^6.2.5
  vue-json-viewer: ^3.0.4
  vue-tippy: ^6.6.0
