export const COUNTRY_DATA = [
  { id: '1', en: 'Angola', cn: '安哥拉', short: 'AO' },
  { id: '2', en: 'Afghanistan', cn: '阿富汗', short: 'AF' },
  { id: '3', en: 'Albania', cn: '阿尔巴尼亚', short: 'AL' },
  { id: '4', en: 'Algeria', cn: '阿尔及利亚', short: 'DZ' },
  { id: '5', en: 'Andorra', cn: '安道尔共和国', short: 'AD' },
  { id: '6', en: 'Anguilla', cn: '安圭拉岛', short: 'AI' },
  { id: '7', en: 'Antigua and Barbuda', cn: '安提瓜和巴布达', short: 'AG' },
  { id: '8', en: 'Argentina', cn: '阿根廷', short: 'AR' },
  { id: '9', en: 'Armenia', cn: '亚美尼亚', short: 'AM' },
  { id: '10', en: 'Australia', cn: '澳大利亚', short: 'AU' },
  { id: '11', en: 'Austria', cn: '奥地利', short: 'AT' },
  { id: '12', en: 'Azerbaijan', cn: '阿塞拜疆', short: 'AZ' },
  { id: '13', en: 'Bahamas', cn: '巴哈马', short: 'BS' },
  { id: '14', en: 'Bahrain', cn: '巴林', short: 'BH' },
  { id: '15', en: 'Bangladesh', cn: '孟加拉国', short: 'BD' },
  { id: '16', en: 'Barbados', cn: '巴巴多斯', short: 'BB' },
  { id: '17', en: 'Belarus', cn: '白俄罗斯', short: 'BY' },
  { id: '18', en: 'Belgium', cn: '比利时', short: 'BE' },
  { id: '19', en: 'Belize', cn: '伯利兹', short: 'BZ' },
  { id: '20', en: 'Benin', cn: '贝宁', short: 'BJ' },
  { id: '21', en: 'Bermuda', cn: '百慕大群岛', short: 'BM' },
  { id: '22', en: 'Bolivia', cn: '玻利维亚', short: 'BO' },
  { id: '23', en: 'Botswana', cn: '博茨瓦纳', short: 'BW' },
  { id: '24', en: 'Brazil', cn: '巴西', short: 'BR' },
  { id: '25', en: 'Brunei', cn: '文莱', short: 'BN' },
  { id: '26', en: 'Bulgaria', cn: '保加利亚', short: 'BG' },
  { id: '27', en: 'Burkina-faso', cn: '布基纳法索', short: 'BF' },
  { id: '28', en: 'Burma', cn: '缅甸', short: 'MM' },
  { id: '29', en: 'Burundi', cn: '布隆迪', short: 'BI' },
  { id: '30', en: 'Cameroon', cn: '喀麦隆', short: 'CM' },
  { id: '31', en: 'Canada', cn: '加拿大', short: 'CA' },
  { id: '32', en: 'Central African Republic', cn: '中非共和国', short: 'CF' },
  { id: '33', en: 'Chad', cn: '乍得', short: 'TD' },
  { id: '34', en: 'Chile', cn: '智利', short: 'CL' },
  { id: '35', en: 'Colombia', cn: '哥伦比亚', short: 'CO' },
  { id: '36', en: 'Congo', cn: '刚果', short: 'CG' },
  { id: '37', en: 'Cook Is', cn: '库克群岛', short: 'CK' },
  { id: '38', en: 'Costa Rica', cn: '哥斯达黎加', short: 'CR' },
  { id: '39', en: 'Cuba', cn: '古巴', short: 'CU' },
  { id: '40', en: 'Cyprus', cn: '塞浦路斯', short: 'CY' },
  { id: '41', en: 'Czech Republic', cn: '捷克', short: 'CZ' },
  { id: '42', en: 'Denmark', cn: '丹麦', short: 'DK' },
  { id: '43', en: 'Djibouti', cn: '吉布提', short: 'DJ' },
  { id: '44', en: 'Dominica Rep', cn: '多米尼加共和国', short: 'DO' },
  { id: '45', en: 'Ecuador', cn: '厄瓜多尔', short: 'EC' },
  { id: '46', en: 'Egypt', cn: '埃及', short: 'EG' },
  { id: '47', en: 'EI Salvador', cn: '萨尔瓦多', short: 'SV' },
  { id: '48', en: 'Estonia', cn: '爱沙尼亚', short: 'EE' },
  { id: '49', en: 'Ethiopia', cn: '埃塞俄比亚', short: 'ET' },
  { id: '50', en: 'Fiji', cn: '斐济', short: 'FJ' },
  { id: '51', en: 'Finland', cn: '芬兰', short: 'FI' },
  { id: '52', en: 'France', cn: '法国', short: 'FR' },
  { id: '53', en: 'French Guiana', cn: '法属圭亚那', short: 'GF' },
  { id: '54', en: 'Gabon', cn: '加蓬', short: 'GA' },
  { id: '55', en: 'Gambia', cn: '冈比亚', short: 'GM' },
  { id: '56', en: 'Georgia', cn: '格鲁吉亚', short: 'GE' },
  { id: '57', en: 'Germany', cn: '德国', short: 'DE' },
  { id: '58', en: 'Ghana', cn: '加纳', short: 'GH' },
  { id: '59', en: 'Gibraltar', cn: '直布罗陀', short: 'GI' },
  { id: '60', en: 'Greece', cn: '希腊', short: 'GR' },
  { id: '61', en: 'Grenada', cn: '格林纳达', short: 'GD' },
  { id: '62', en: 'Guam', cn: '关岛', short: 'GU' },
  { id: '63', en: 'Guatemala', cn: '危地马拉', short: 'GT' },
  { id: '64', en: 'Guinea', cn: '几内亚', short: 'GN' },
  { id: '65', en: 'Guyana', cn: '圭亚那', short: 'GY' },
  { id: '66', en: 'Haiti', cn: '海地', short: 'HT' },
  { id: '67', en: 'Honduras', cn: '洪都拉斯', short: 'HN' },
  { id: '68', en: 'Hongkong', cn: '香港', short: 'HK' },
  { id: '69', en: 'Hungary', cn: '匈牙利', short: 'HU' },
  { id: '70', en: 'Iceland', cn: '冰岛', short: 'IS' },
  { id: '71', en: 'India', cn: '印度', short: 'IN' },
  { id: '72', en: 'Indonesia', cn: '印度尼西亚', short: 'ID' },
  { id: '73', en: 'Iran', cn: '伊朗', short: 'IR' },
  { id: '74', en: 'Iraq', cn: '伊拉克', short: 'IQ' },
  { id: '75', en: 'Ireland', cn: '爱尔兰', short: 'IE' },
  { id: '76', en: 'Israel', cn: '以色列', short: 'IL' },
  { id: '77', en: 'Italy', cn: '意大利', short: 'IT' },
  { id: '78', en: 'Jamaica', cn: '牙买加', short: 'JM' },
  { id: '79', en: 'Japan', cn: '日本', short: 'JP' },
  { id: '80', en: 'Jordan', cn: '约旦', short: 'JO' },
  { id: '81', en: 'Cambodia', cn: '柬埔寨', short: 'KH' },
  { id: '82', en: 'Kazakstan', cn: '哈萨克斯坦', short: 'KZ' },
  { id: '83', en: 'Kenya', cn: '肯尼亚', short: 'KE' },
  { id: '84', en: 'Korea', cn: '韩国', short: 'KR' },
  { id: '85', en: 'Kuwait', cn: '科威特', short: 'KW' },
  { id: '86', en: 'Kyrgyzstan', cn: '吉尔吉斯坦', short: 'KG' },
  { id: '87', en: 'Laos', cn: '老挝', short: 'LA' },
  { id: '88', en: 'Latvia', cn: '拉脱维亚', short: 'LV' },
  { id: '89', en: 'Lebanon', cn: '黎巴嫩', short: 'LB' },
  { id: '90', en: 'Lesotho', cn: '莱索托', short: 'LS' },
  { id: '91', en: 'Liberia', cn: '利比里亚', short: 'LR' },
  { id: '92', en: 'Libya', cn: '利比亚', short: 'LY' },
  { id: '93', en: 'Liechtenstein', cn: '列支敦士登', short: 'LI' },
  { id: '94', en: 'Lithuania', cn: '立陶宛', short: 'LT' },
  { id: '95', en: 'Luxembourg', cn: '卢森堡', short: 'LU' },
  { id: '96', en: 'Macao', cn: '澳门', short: 'MO' },
  { id: '97', en: 'Madagascar', cn: '马达加斯加', short: 'MG' },
  { id: '98', en: 'Malawi', cn: '马拉维', short: 'MW' },
  { id: '99', en: 'Malaysia', cn: '马来西亚', short: 'MY' },
  { id: '100', en: 'Maldives', cn: '马尔代夫', short: 'MV' },
  { id: '101', en: 'Mali', cn: '马里', short: 'ML' },
  { id: '102', en: 'Malta', cn: '马耳他', short: 'MT' },
  { id: '103', en: 'Mauritius', cn: '毛里求斯', short: 'MU' },
  { id: '104', en: 'Mexico', cn: '墨西哥', short: 'MX' },
  { id: '105', en: 'Moldova', cn: '摩尔多瓦', short: 'MD' },
  { id: '106', en: 'Monaco', cn: '摩纳哥', short: 'MC' },
  { id: '107', en: 'Mongolia', cn: '蒙古', short: 'MN' },
  { id: '108', en: 'Montserrat Is', cn: '蒙特塞拉特岛', short: 'MS' },
  { id: '109', en: 'Morocco', cn: '摩洛哥', short: 'MA' },
  { id: '110', en: 'Mozambique', cn: '莫桑比克', short: 'MZ' },
  { id: '111', en: 'Namibia', cn: '纳米比亚', short: 'NA' },
  { id: '112', en: 'Nauru', cn: '瑙鲁', short: 'NR' },
  { id: '113', en: 'Nepal', cn: '尼泊尔', short: 'NP' },
  { id: '114', en: 'Netherlands', cn: '荷兰', short: 'NL' },
  { id: '115', en: 'New Zealand', cn: '新西兰', short: 'NZ' },
  { id: '116', en: 'Nicaragua', cn: '尼加拉瓜', short: 'NI' },
  { id: '117', en: 'Niger', cn: '尼日尔', short: 'NE' },
  { id: '118', en: 'Nigeria', cn: '尼日利亚', short: 'NG' },
  { id: '119', en: 'North Korea', cn: '朝鲜', short: 'KP' },
  { id: '120', en: 'Norway', cn: '挪威', short: 'NO' },
  { id: '121', en: 'Oman', cn: '阿曼', short: 'OM' },
  { id: '122', en: 'Pakistan', cn: '巴基斯坦', short: 'PK' },
  { id: '123', en: 'Panama', cn: '巴拿马', short: 'PA' },
  { id: '124', en: 'Papua New Cuinea', cn: '巴布亚新几内亚', short: 'PG' },
  { id: '125', en: 'Paraguay', cn: '巴拉圭', short: 'PY' },
  { id: '126', en: 'Peru', cn: '秘鲁', short: 'PE' },
  { id: '127', en: 'Philippines', cn: '菲律宾', short: 'PH' },
  { id: '128', en: 'Poland', cn: '波兰', short: 'PL' },
  { id: '129', en: 'French Polynesia', cn: '法属玻利尼西亚', short: 'PF' },
  { id: '130', en: 'Portugal', cn: '葡萄牙', short: 'PT' },
  { id: '131', en: 'Puerto Rico', cn: '波多黎各', short: 'PR' },
  { id: '132', en: 'Qatar', cn: '卡塔尔', short: 'QA' },
  { id: '133', en: 'Romania', cn: '罗马尼亚', short: 'RO' },
  { id: '134', en: 'Russia', cn: '俄罗斯', short: 'RU' },
  { id: '135', en: 'Saint Lueia', cn: '圣卢西亚', short: 'LC' },
  { id: '136', en: 'Saint Vincent', cn: '圣文森特岛', short: 'VC' },
  { id: '137', en: 'San Marino', cn: '圣马力诺', short: 'SM' },
  { id: '138', en: 'Sao Tome and Principe', cn: '圣多美和普林西比', short: 'ST' },
  { id: '139', en: 'Saudi Arabia', cn: '沙特阿拉伯', short: 'SA' },
  { id: '140', en: 'Senegal', cn: '塞内加尔', short: 'SN' },
  { id: '141', en: 'Seychelles', cn: '塞舌尔', short: 'SC' },
  { id: '142', en: 'Sierra Leone', cn: '塞拉利昂', short: 'SL' },
  { id: '143', en: 'Singapore', cn: '新加坡', short: 'SG' },
  { id: '144', en: 'Slovakia', cn: '斯洛伐克', short: 'SK' },
  { id: '145', en: 'Slovenia', cn: '斯洛文尼亚', short: 'SI' },
  { id: '146', en: 'Solomon Is', cn: '所罗门群岛', short: 'SB' },
  { id: '147', en: 'Somali', cn: '索马里', short: 'SO' },
  { id: '148', en: 'South Africa', cn: '南非', short: 'ZA' },
  { id: '149', en: 'Spain', cn: '西班牙', short: 'ES' },
  { id: '150', en: 'Sri Lanka', cn: '斯里兰卡', short: 'LK' },
  { id: '151', en: 'St Lucia', cn: '圣卢西亚', short: 'LC' },
  { id: '152', en: 'St Vincent', cn: '圣文森特', short: 'VC' },
  { id: '153', en: 'Sudan', cn: '苏丹', short: 'SD' },
  { id: '154', en: 'Suriname', cn: '苏里南', short: 'SR' },
  { id: '155', en: 'Swaziland', cn: '斯威士兰', short: 'SZ' },
  { id: '156', en: 'Sweden', cn: '瑞典', short: 'SE' },
  { id: '157', en: 'Switzerland', cn: '瑞士', short: 'CH' },
  { id: '158', en: 'Syria', cn: '叙利亚', short: 'SY' },
  { id: '159', en: 'Taiwan', cn: '台湾', short: 'TW' },
  { id: '160', en: 'Tajikstan', cn: '塔吉克斯坦', short: 'TJ' },
  { id: '161', en: 'Tanzania', cn: '坦桑尼亚', short: 'TZ' },
  { id: '162', en: 'Thailand', cn: '泰国', short: 'TH' },
  { id: '163', en: 'Togo', cn: '多哥', short: 'TG' },
  { id: '164', en: 'Tonga', cn: '汤加', short: 'TO' },
  { id: '165', en: 'Trinidad and Tobago', cn: '特立尼达和多巴哥', short: 'TT' },
  { id: '166', en: 'Tunisia', cn: '突尼斯', short: 'TN' },
  { id: '167', en: 'Turkey', cn: '土耳其', short: 'TR' },
  { id: '168', en: 'Turkmenistan', cn: '土库曼斯坦', short: 'TM' },
  { id: '169', en: 'Uganda', cn: '乌干达', short: 'UG' },
  { id: '170', en: 'Ukraine', cn: '乌克兰', short: 'UA' },
  { id: '171', en: 'United Arab Emirates', cn: '阿拉伯联合酋长国', short: 'AE' },
  { id: '172', en: 'Kiongdom', cn: '英国', short: 'GB' },
  { id: '173', en: 'United States', cn: '美国', short: 'US' },
  { id: '174', en: 'Uruguay', cn: '乌拉圭', short: 'UY' },
  { id: '175', en: 'Uzbekistan', cn: '乌兹别克斯坦', short: 'UZ' },
  { id: '176', en: 'Venezuela', cn: '委内瑞拉', short: 'VE' },
  { id: '177', en: 'Vietnam', cn: '越南', short: 'VN' },
  { id: '178', en: 'Yemen', cn: '也门', short: 'YE' },
  { id: '179', en: 'Yugoslavia', cn: '南斯拉夫', short: 'YU' },
  { id: '180', en: 'Zimbabwe', cn: '津巴布韦', short: 'ZW' },
  { id: '181', en: 'Zaire', cn: '扎伊尔', short: 'ZR' },
  { id: '182', en: 'Zambia', cn: '赞比亚', short: 'ZM' },
];
